### ISSUE TITLE
Increase TPS top dead zone > 5%

### ISSUE THREAD

**Issue by RustyPedrosa** [spartanracingelectric/VCU#112]
If APPS flicks back hard during calibration, the min voltage may be lower than possible under normal driving.  Until a hardware fix is determined, we can mitigate this by increasing the deadzone at the top of the pedal.  Currently, drivers are pressing lightly on the throttle to artificially crate this deadzone anyway.
0.655V stop
0.57 or lower if pedal is pulled back
calibmax 1.844

**Comment by vsawce** [comment]
Will need to validate with new APPS sensors for SRE-6/SR13
