### ISSUE TITLE
Handle CAN messages from Ennoid BMS

### ISSUE THREAD

**Issue by RustyPedrosa** [spartanracingelectric/VCU#115]

**Comment by RustyPedrosa** [comment]
https://github.com/spartanracingelectric/SRE-BMS-Firmware/blob/master/Modules/Src/modCAN.c
For dbc file, see git hash 20b1209a614d2120a519ed88a550249915fe49cc

**Comment by seanlinc** [comment]
Check this out for DBC support

https://github.com/spartanracingelectric/SRE-BMS-Firmware/blob/master/Modules/Inc/sre_dbc.h

**Comment by vsawce** [comment]
No longer using ENNOID BMS.
