### ISSUE TITLE
WSS has no reading and potential SW issue

### ISSUE THREAD

**Issue by seanlinc** [spartanracingelectric/VCU#116]
07/01/2021:

Before shipping the car to the competition, I checked the output from WSS on car by using VCU power and hook the WSS output line to an oscilloscope. Basically no output there, it can be a VCU connector harness issue or WSS sensor dead, or WSS mounting point issue. 

06/29/2021:

WSS object and Sensor_WSS object are both declared as `float4`

When get frequency or pulse by using HY_TTC's API

`IO_PWD_FreqGet( ubyte1 timer_channel, ubyte2 * const frequency )` parameter is a `ubyte2 (uint16_t)` pointer. Maybe potential issues in here

`IO_PWD_PulseGet( ubyte1 timer_channel, ubyte4 * const pulse_width )` will take `ubyte4` pointer, which also incorrect to use because float4 is signed

Should we also remove WSS objects and functions in `sensor.c` to `wheelSpeed.c` instead of using extern variables

**Comment by vsawce** [comment]
As of 1/23/2022, WSS reading minimal functionality is fixed. May need to do calibration with VCU-outputted value and actual value, however.
