### ISSUE TITLE
Determine if sensors.c ubyte4 sensorValue can be changed to ubyte2

### ISSUE THREAD

**Issue by RustyPedrosa** [spartanracingelectric/VCU#121]
When PR #120 merges, if WSS was the only ubyte4 sensor value, then we should probably change the datatype to ubyte2 so we don't waste 2 bytes of memory for every single sensor object.  This is a risk if we do end up using something for which the API returns a 4 byte value though

**Comment by TheEppicJR** [comment]
Suggestion is done in #160
