### ISSUE TITLE
WSS: Is there a reason to look for rising vs falling edge?

### ISSUE THREAD

**Issue by RustyPedrosa** [spartanracingelectric/VCU#122]
//Maybe look for falling edge because we're using NPN/sinking WSS?

**Comment by vsawce** [comment]
@RustyPedrosa Do we still want to know the answer to this if the WSS are good to go?

**Comment by vsawce** [comment]
Doesn't seem like a relevant discussion anymore, will close unless you think this is important @RustyPedrosa
