### ISSUE TITLE
Support DRS implementation

### ISSUE THREAD

**Issue by vsawce** [spartanracingelectric/VCU#136]
**Requirements**
- Digital Input from steering wheel button
- Analog input from rotary switch
- Two outputs to trigger both solenoids, one output per solenoid
- Sensor input (may need to feed traditionally MoTeC-only sensors into VCU)
    - APPS, BPS, WSS currently on VCU side
    - Steering angle, potentially IMU

**Need to further discuss with Josue and Josie**
- High or low active output?

**Rough Logic**
To be filled out, need block diagram from Chavo to start discussion

**Comment by shibcreate** [comment]
Notes: High side active output confirmed
