### ISSUE TITLE
Rewrite/adapt motorcontroller.c

### ISSUE THREAD

**Issue by shibcreate** [spartanracingelectric/VCU#142]
Identify any differences in messages between the two busses ( different CAN IDs / motor controller IDs)
For bench, we can send same torque value to all four motors

**Comment by RustyPedrosa** [comment]
![image](https://user-images.githubusercontent.com/6540111/219642177-a60c2d66-64ac-415c-a088-e254667911e4.png)

**Comment by shibcreate** [comment]
![image](https://user-images.githubusercontent.com/98338989/228673243-152ab87e-f8f0-4b0a-94d8-2527d2fd04cf.png)
![image](https://user-images.githubusercontent.com/98338989/228673290-57ada454-7515-4937-81a6-a041a730b2de.png)
