### ISSUE TITLE
Update can manager with new CAN message requirements

### ISSUE THREAD

**Issue by shibcreate** [spartanracingelectric/VCU#143]
Need to remove 0xC0 message and replace with 0x184 (FL), 185 (FR), 188 (RL), 189 (RR)
Move motor control message out of debug message function, OR rename debug message function to SendAllMessages (not important, just a naming thing)

**Comment by RustyPedrosa** [comment]
## Accel / brake / regen behavior
![image](https://user-images.githubusercontent.com/6540111/219608861-ab351f12-2279-43bc-b9d2-e4e20753bc85.png)
![image](https://user-images.githubusercontent.com/6540111/219608934-fa6f2715-de81-49f2-bf0f-9009f37014a4.png)
pg 83-84
