### ISSUE TITLE
Need to create new CAN message structure for AMK controllers

### ISSUE THREAD

**Issue by shibcreate** [spartanracingelectric/VCU#144]
All four torque values are on different CAN message IDs but should only be two per bus (fronts CAN0, rear CAN1)

**Comment by RustyPedrosa** [comment]
## Message IDs
### Base IDs
![image](https://user-images.githubusercontent.com/6540111/219596286-bef402fb-2c9e-46e4-a8aa-ac56da3c93e4.png)

### Actual IDs (per inverter)
![image](https://user-images.githubusercontent.com/6540111/219596372-e370fd5e-3f45-41f6-91bd-cd3603b350d1.png)

## Message Types
3 messages per inverter:
- Actual Values (x2) = From motor controller to VCU (we need to listen for and respond to these).  pg 66
- Setpoints = From VCU to motor controller (we need to send these).  pg 65-66
![image](https://user-images.githubusercontent.com/6540111/219596660-b6fe3687-beac-4a02-a899-f0d2a1036a38.png)

### Actual Values
![image](https://user-images.githubusercontent.com/6540111/219597189-c9f7f5d0-aa45-421d-ad49-f2b8ef710a08.png)
![image](https://user-images.githubusercontent.com/6540111/219600029-6ad86dee-4438-4d73-b5f7-807c7f36d082.png)

### Setpoints
![image](https://user-images.githubusercontent.com/6540111/219600128-4b95b18b-9652-49fa-af8a-1c11d6604dc4.png)

Note: 50ms heartbeat for Setpoints messages
![image](https://user-images.githubusercontent.com/6540111/219600319-38778d80-9b11-4d07-a52b-5dd4ee62e838.png)
