### ISSUE TITLE
Activate the I²t monitoring of the servo motor in ID32773 'Service bits', bit 14

### ISSUE THREAD

**Issue by RustyPedrosa** [spartanracingelectric/VCU#145]
Is this something we have to explicitly enable?  Or is it already activated by default?

![image](https://user-images.githubusercontent.com/6540111/219582255-4fe5094b-842a-480d-b08c-4bc43a0528c8.png)

**Comment by shibcreate** [comment]
![image](https://user-images.githubusercontent.com/98338989/228658482-80ca0605-09d7-49bf-bee2-92b820d1f7a2.png)

We can set this on the AMK software side
