### ISSUE TITLE
Add VCU input for precharge complete

### ISSUE THREAD

**Issue by RustyPedrosa** [spartanracingelectric/VCU#152]
As part of the AMK startup procedure, the VCU needs to flip a bit in the Setpoints messages when precharge is complete,

![image](https://user-images.githubusercontent.com/6540111/227456804-339db347-3e66-46ef-abc0-23891f39b130.png)

Square = action performed by AMK inverters
Octagon = action we need to perform
orange text = my comments

In order to do this, the VCU needs a way to know when precharge is done.  This is different behavior from the Rinehart, which precharged by itself.

The VCU does have an input for HVILTerminationSense, but that signal going high indicates that we can START precharging, not that it has completed.

**Comment by shibcreate** [comment]
We can utilize the AMK minimim precharge voltage fault. If the AMK's don't see the minimum voltage necessary after precharge it will fault. So for the time being we can have a time delay after HVIL sense to enable precharge, send the command, listen to AMKs signals & AMK faults to verify the minimum bus voltage is met.
