### ISSUE TITLE
Change to OOP instead of using global objects/etc

### ISSUE THREAD

**Issue by RustyPedrosa** [spartanracingelectric/VCU#19]
All of our objects (sensors, motor controller, etc) should probably be changed from global structs/etc to objects with proper encapsulation/etc.
http://stackoverflow.com/questions/10320025/c-private-variables-get-and-set-methods
http://stackoverflow.com/questions/11481423/how-to-use-a-function-pointer-in-a-c-struct
http://www.codeproject.com/Tips/800474/Function-Pointer-in-C-Struct

**Comment by GuySmily** [comment]
This is still in progress.

**Comment by GuySmily** [comment]
Want to get rid of initializations.c and fix sensors.c
