### ISSUE TITLE
Add MotorController_clearFaults() function

### ISSUE THREAD

**Issue by RustyPedrosa** [spartanracingelectric/VCU#25]
Add MotorController_clearFaults() to motorController.c/.h
- Should set a flag in a motorcontroller object (mcu0.commands?)
  Add an output function for message ID 0xC1 to canOutput.c
- Check for flag
  Add an input case for message 0xC2 to canInput.c for comfirmation message?
- Clear command flag

See RMS CAN manual (2.3 Parameter Messages)

**Comment by GuySmily** [comment]
Not needed if we're just going to powercycle motor controller by toggling HV.  HVIL term sense will shut motor controller off/on.
