### ISSUE TITLE
Read MCM and BMS faults, set flags in those objects, store faults in EEPROM, broadcast over CAN

### ISSUE THREAD

**Issue by RustyPedrosa** [spartanracingelectric/VCU#27]

**Comment by GuySmily** [comment]
State machine is not necessary.

Faults should be stored such that any previous fault is remembered even if it later goes away by itself.  Faults should be stored in EEPROM until cleared.  (How?)

Stored faults should be broadcast over CAN every ? seconds.

This should be done for BMS and MCM.
