### ISSUE TITLE
POST

### ISSUE THREAD

**Issue by RustyPedrosa** [spartanracingelectric/VCU#43]
Investigate whether we should have a Power On Self Test. Make sure ADC comes online without problems. Make sure valid readings are returned from all sensors. Check CAN buses. Make sure eeprom data makes sense. Do other startup checks.

**Comment by GuySmily** [comment]
POST is the best time to perform certain tests.  There are certain pins described in the VCU manuals that can be tested by cycling them on and off.  These tests should be performed during POST.
