### ISSUE TITLE
Dash messages

### ISSUE THREAD

**Issue by RustyPedrosa** [spartanracingelectric/VCU#46]
Implement dash message and beep CAN messages

Beep 0x510
- Bytes 0-1: Frequency (tone), Hz (31-65535)
- Bytes 2-3: Duty (beeping vs quiet time) % (0-FF, 0 = off / no beep)
- Bytes 4-6 Period (time on + time off) ms
- Byte 7: Burst (# of beeps, 0 = unlimited/continuous)

Display Message (errors/etc) 0x511-0x514
- 8 bytes: 8 characters
- Repeat CAN message until message should stop being displayed - will turn off after 2 seconds
- Future, 4 message IDs to fill whole screen

**Comment by GuySmily** [comment]
Potential messages:
Loss of comm with CAN devices (BMS, MCM)
Implausibility
Regen disabled due to speed minimum
Calibration instructions
Other things that might otherwise seem out-of-the-ordinary to the driver (car doing anything that doesn't match driver input)

**Comment by GuySmily** [comment]
Need to create a table of IO_E_blabla codes and messages that should be displayed on the dash when they occur.
See safety.c
