### ISSUE TITLE
Add MCM Relay to Startup Sequence

### ISSUE THREAD

**Issue by RustyPedrosa** [spartanracingelectric/VCU#50]
Don't turn the motor controller on until HVIL Term Sense goes high.

This is a separate task from adding MCM and HVIL objects and ADC Inits (#30)

**Comment by GuySmily** [comment]
Currently in sensors.c.
Relay needs to be made into proper object with error handling support.  Maybe just make it a Sensor object.

**Comment by GuySmily** [comment]
Moved to MCM_relayControl() but still changing pin directly instead of thru object,
