### ISSUE TITLE
Limit regen @ 300V, 80kW, ?mph, cell limits (amps, temp, etc)...

### ISSUE THREAD

**Issue by RustyPedrosa** [spartanracingelectric/VCU#57]
Possibility of regen creating momentary voltage surge above 300V?

EV2.2.4 A violation is defined as using more than 80kW or exceeding the specified voltage for more than 100ms continuously or using more than 80kW or exceeding the specified voltage, after a moving average over 500ms is applied.

**Comment by GuySmily** [comment]
Speed limit
Temperature
Voltage
amperage (32A)
Default (no pedal input) = 10% regen

**Comment by GuySmily** [comment]
These limits should apply to both directions (regen and accel)

**Comment by GuySmily** [comment]
Obey battery amperage burst limits
Ramp if possible

**Comment by GuySmily** [comment]
2.2.3.2 CAN Torque command:
For a forward direction command:
 Positive torque command will give a positive torque feedback and is motoring for positive speed.
 Negative torque command will give a negative torque feedback and is regen for positive speed.
 Positive torque command will give a positive torque feedback and is regen for negative speed.
 A negative torque command should not be allowed if already going negative speed.

**Comment by GuySmily** [comment]
All done except 300V limit (does mcm do this?)

**Comment by chucktesta154k** [comment]
No. We just stop charging at 300

**Comment by GuySmily** [comment]
Does the motor controller automatically limit it to 300v? Was this limit
programmed into eeprom already? Do we know/Are we just assuming that it
won't surge back up that high? If we're all safe then we can cut that
requirement out and label this as ready to test

**Comment by chucktesta154k** [comment]
We could have an issue with regen while fully charged. So maybe its worth
trying to implemebt
