### ISSUE TITLE
Detect loss of MCM heartbeat (timeout) and reset startupStage

### ISSUE THREAD

**Issue by RustyPedrosa** [spartanracingelectric/VCU#67]
If the motor controller communication is lost (mcm turned off, can problem, etc),  MotorControllerPowerManagement should handle this.

If MCM comes back up, should inverter be re-enabled without requiring RTD procedure?  (RTD light can blink to indicate that MCM was lost but drive will resume automatically).

**Comment by alexsternberg** [comment]
Not sure offhand if this is specified in the rules. However, it may be
'good engineering practice' to require a full RTD cycle.

**Comment by chucktesta154k** [comment]
We should talk about this and the process handling of different shutdowns,
be it on purpose or accident.
