### ISSUE TITLE
MCM_getPower and BMS_getPower: incorrect values in calcs + data overflow

### ISSUE THREAD

**Issue by RustyPedrosa** [spartanracingelectric/VCU#83]
MCM_getPower and BMS_getPower: incorrect values are returned due to
CAN data multiplier not being accounted for.  Even after values are corrected, ubyte2 will overflow.  The
return type must be changed to ubyte4 to support > 65535 watts.

**Comment by TheEppicJR** [comment]
All now fixed some time prior to #160
