### ISSUE TITLE
Figure out which motor controller temps to use for cooling / torque reduction

### ISSUE THREAD

**Issue by RustyPedrosa** [spartanracingelectric/VCU#90]
Function to update:
motorController.c MCM_getTemp()

Needed by:
safety.c  SafetyChecker_reduceTorque()
cooling.c CoolingSystem_calculations()

**Comment by GuySmily** [comment]
There are a bunch of different temperatures reported by the motor controller.  Figure out which one to use for temp calcs, or maybe select the max() of all temps?
